<h1>Категории</h1>
<a href="/admin/category/add/">Добавить</a><br><br>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('
    <div%s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error', ['alert', 'alert-dismissable'], 'alert-danger');
    echo $flash->render('info', ['alert', 'alert-dismissable'], 'alert-info');
    echo $flash->render('default', ['alert', 'alert-dismissable'], 'alert-warning');
    echo $flash->render('success', ['alert', 'alert-dismissable'], 'alert-success');
?>
<table class="table table-striped table-hover ">
    <tbody>
    <tr>
        <td>#</td>
        <td>Ключ</td>
        <td>Название</td>
        <td>Действие</td>
    </tr>
    <?php

        foreach ($category as $item) {
            echo "<tr>
                    <td>{$item->getId()}</td>
                    <td>{$item->getCategoryKey()}</td>
                    <td>{$item->getCategoryName()}</td>
                    <td><a href={$this->url('admin/category', ['action' => 'edit', 'id' => $item->getId()])}>Редактировать</a>
                    <a href={$this->url('admin/category', ['action' => 'delete', 'id' => $item->getId()])}>Удалить</a></td>
                  </tr>";
        }
    ?>
    </tbody>
</table>